# DATASCIENCE 2023
a simple reminder for quick use

##### Життєвий цикл проєкту Data Science

- `OBTAIN` (Збір даних до CSV, JSON або XML)<br>
- `SCRUB` (Очищення та підготовка даних. сміття на вхід - сміття на вихід)<br>
-- Видалення дублікатів<br>
-- Видалення відсутніх значень<br>
-- Кодування категоріальних даних в числові значення<br>
-- Нормалізація даних, щоб забезпечити рівні ваги для всіх факторів<br>
- `EXPLORE` (Дослідження даних. EDA (Exploratory Data Analysis))<br>
-- Збір інформації про дані.<br>
-- Зрозуміти, які можливості наявні у ваших даних і як їх краще аналізувати.<br>
-- Візуалізація даних.<br>
- `MODEL` (Створення моделі)<br>
-- scikit-learn<br>
-- TensorFlow<br>
-- PyTorch<br>
- `INTERPRET` - Інтерпретація (Застосування)<br>

##### numpy - array

In [5]:
import numpy as np


np.array([el for el in range(1, 11)])  # ndarray [1  2  3  4  5  6  7  8  9 10]
np.arange(1, 11)  # ndarray [1  2  3  4  5  6  7  8  9 10]
np.linspace(1, 10, num=10)  # ndarray [1.  2.  3.  4.  5  6.  7.  8.  9. 10.]
np.zeros((3, 5), dtype=int)  # ndarray [[0 0 0 0 0], [0 0 0 0 0], [0 0 0 0 0]]
np.array([5 for _ in range(5)])
np.array([[5 for _ in range(4)] for __ in range(3)])
np.random.randint(1, 11, size=(3, 5))  # ndarray [[6  4  4  2  3], [5  9  9  2 10], [10  4  8  2  8]]
np.random.rand(2, 2)  # ndarray [[0.16002009 0.35987033], [0.28608734 0.62922585]]

v2 = np.random.randint(1, 11, size=5)  # ndarray [6 1 6 5 5]
v3 = np.random.randint(1, 11, size=5)  # ndarray [1 2 8 3 7]
print('sum:\n', v2 + v3)  # ndarray [ 7  3 14  8 12]
print('subtraction:\n', v2 - v3)  # ndarray [ 5 -1 -2  2 -2]
print('multiplication:\n', v2 * v3)  # ndarray [ 6  2 48 15 35]
print(np.dot(v2, v3))  # 106 = 6+2+48+15+35
print(v2 @ v3)  # 106 
type(v3)  # numpy.ndarray

m6 = np.random.randint(1, 11, size=(3, 3))  # ndarray [[ 7  5  3],  [ 1 10  4],  [ 5  6  3]]
print(f'M6= \n{m6}\n')
m6_inv = np.linalg.inv(m6)  # ndarray [[ -1.2  -0.6   2. ], [ -3.4  -1.2   5. ], [  8.8   3.4 -13. ]]
print('inverse:')
print(m6_inv)

m6T = m6.T
print(f'\n{m6T=}\n')

m10 = np.random.randint(1, 11, size=(3, 2))
m11 = np.random.randint(1, 11, size=(3, 2))
print(m10 * m11)
print(np.multiply(m10, m11))
print(m10.sum())
print(np.sum(m10))

print(np.array([[el.sum()] for el in m10[:]]))
print(np.array([[m10[el][:].sum()] for el in range(m10.shape[0])]))
print(np.sum(m10, axis=1).reshape((m10.shape[0], 1)))

print(m10 * m10)
print(m10 ** 2)
print(np.square(m10))

print(m10 ** 0.5)
print(np.sqrt(m10))

a = np.array([0, 2])
positive = a <= 1
print(positive)  # [ True False]
print(a.shape[0])  # 2

sum:
 [ 7 12  9 11 10]
subtraction:
 [-5 -4 -5  5 -4]
multiplication:
 [ 6 32 14 24 21]
97
97
M6= 
[[ 8  1  7]
 [ 9  7  3]
 [ 9  8 10]]

inverse:
[[ 0.125       0.125      -0.125     ]
 [-0.17119565  0.04619565  0.10597826]
 [ 0.02445652 -0.14945652  0.12771739]]

m6T=array([[ 8,  9,  9],
       [ 1,  7,  8],
       [ 7,  3, 10]])

[[36  9]
 [ 9 48]
 [12 24]]
[[36  9]
 [ 9 48]
 [12 24]]
31
31
[[10]
 [ 9]
 [12]]
[[10]
 [ 9]
 [12]]
[[10]
 [ 9]
 [12]]
[[81  1]
 [ 1 64]
 [36 36]]
[[81  1]
 [ 1 64]
 [36 36]]
[[81  1]
 [ 1 64]
 [36 36]]
[[3.         1.        ]
 [1.         2.82842712]
 [2.44948974 2.44948974]]
[[3.         1.        ]
 [1.         2.82842712]
 [2.44948974 2.44948974]]
[ True False]
2


##### pandas - DataFrame

In [6]:
import pandas as pd


df = pd.read_csv('bikes_rent.csv')
df.head(3)
df.tail(3)

# Видаліть з таблиці останній рядок таблиці
ndf = df.drop(df.shape[0]-1)
ndf.tail(3)

# Замініть відсутні дані в стовпцях середніми значеннями цих стовпців (метод fillna)
ndf2 = ndf.fillna({key: ndf[key].mean() for key in ndf.columns[1:]})

df['yr']  # Series - column from DataFrame
df[['yr']]  # DataFrame - consist column from DataFrame
df.loc[0]  # Series - line with index-name 0 from DataFrame
df.iloc[1]  # Series - line with number index 1 from DataFrame
df.iloc[:, 1:4]  # DataFrame with all lines and columns with indices 1-3
df.iloc[0:5, 5:8]  # DataFrame
df.iloc[0:5]['yr']  # Series
df.iloc[:, [0, 1, 3]]  # DataFrame
df[0:3]  # DataFrame - lines 0-2
df[df.index % 2 == 0]  # DataFrame
df[df['yr'] == 1]  # DataFrame
df[['yr', 'temp']]  # DataFrame
df[df.columns[:-1]]  # DataFrame
df.iloc[:, 1]  # Series

df.describe()

df.filter(items=[col for col in ('yr', 'season', 'temp')])

df = pd.DataFrame({})
df[df.columns[:-1]]

Empty DataFrame
Columns: []
Index: []

##### corrwith

- https://www.statology.org/pandas-corrwith/

In [7]:
# Data for matrix
data = {'A': [45,37,42,35,39],
        'B': [38,31,26,28,33],
        'C': [10,15,17,21,12]
        }

df = pd.DataFrame(data,columns=['A','B','C'])
print("Original dataframe")
print(df) # original df
print("\n")

corrMatrix = df.corrwith(df["B"]) # finding correlations
print("Between column B and the rest of the dataframe")
print("Correlation Coefficients Matrix")
print(corrMatrix) # printing correlations
print('\n')

corrMatrix = df.corrwith(df["C"]) # finding correlations
print("Between column C and the rest of the dataframe")
print("Correlation Coefficients Matrix")
print(corrMatrix) # printing correlations
print('\n')

corrMatrix = df.corrwith(df["C"]) # finding correlations
print("Between column C and the rest of the dataframe")
print("Correlation Coefficients Matrix")
print(corrMatrix) # printing correlations

Original dataframe
    A   B   C
0  45  38  10
1  37  31  15
2  42  26  17
3  35  28  21
4  39  33  12


Between column B and the rest of the dataframe
Correlation Coefficients Matrix
A    0.518457
B    1.000000
C   -0.860941
dtype: float64


Between column C and the rest of the dataframe
Correlation Coefficients Matrix
A   -0.701886
B   -0.860941
C    1.000000
dtype: float64


Between column C and the rest of the dataframe
Correlation Coefficients Matrix
A   -0.701886
B   -0.860941
C    1.000000
dtype: float64


##### next...

## next...

#### H4

##### H5

###### H6

####### H7

In [8]:
import math as m