# a simple reminder for quick use

### numpy - array

In [3]:
import numpy as np

In [65]:
np.array([el for el in range(1, 11)])  # ndarray [1  2  3  4  5  6  7  8  9 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
np.arange(1, 11)  # ndarray [1  2  3  4  5  6  7  8  9 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
np.linspace(1, 10, num=10)  # ndarray [1.  2.  3.  4.  5  6.  7.  8.  9. 10.]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [68]:
np.zeros((3, 5), dtype=int)  # ndarray [[0 0 0 0 0], [0 0 0 0 0], [0 0 0 0 0]]

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [69]:
np.array([5 for _ in range(5)])

array([5, 5, 5, 5, 5])

In [70]:
np.array([[5 for _ in range(4)] for __ in range(3)])

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [71]:
np.random.randint(1, 11, size=(3, 5))  # ndarray [[6  4  4  2  3], [5  9  9  2 10], [10  4  8  2  8]]

array([[ 6,  2,  3, 10,  4],
       [ 9,  8,  4,  9,  1],
       [ 9,  1, 10,  2,  3]])

In [72]:
np.random.rand(2, 2)  # ndarray [[0.16002009 0.35987033], [0.28608734 0.62922585]]

array([[0.04680412, 0.05376671],
       [0.09169035, 0.52618751]])

In [4]:
v2 = np.random.randint(1, 11, size=5)  # ndarray [6 1 6 5 5]
v3 = np.random.randint(1, 11, size=5)  # ndarray [1 2 8 3 7]
print('sum:\n', v2 + v3)  # ndarray [ 7  3 14  8 12]
print('subtraction:\n', v2 - v3)  # ndarray [ 5 -1 -2  2 -2]
print('multiplication:\n', v2 * v3)  # ndarray [ 6  2 48 15 35]
print(np.dot(v2, v3))  # 106 = 6+2+48+15+35
print(v2 @ v3)  # 106 

sum:
 [15 11  9 16  3]
subtraction:
 [-5 -9  3  4  1]
multiplication:
 [50 10 18 60  2]
140
140


In [5]:
type(v3)  # numpy.ndarray

numpy.ndarray

In [74]:
m6 = np.random.randint(1, 11, size=(3, 3))  # ndarray [[ 7  5  3],  [ 1 10  4],  [ 5  6  3]]
print(f'M6= \n{m6}\n')
m6_inv = np.linalg.inv(m6)  # ndarray [[ -1.2  -0.6   2. ], [ -3.4  -1.2   5. ], [  8.8   3.4 -13. ]]
print('inverse:')
print(m6_inv)

M6= 
[[ 6  8  4]
 [ 6 10  1]
 [ 5  5  2]]

inverse:
[[-0.32608696 -0.08695652  0.69565217]
 [ 0.15217391  0.17391304 -0.39130435]
 [ 0.43478261 -0.2173913  -0.26086957]]


In [75]:
m6T = m6.T
print(f'\n{m6T=}\n')


m6T=array([[ 6,  6,  5],
       [ 8, 10,  5],
       [ 4,  1,  2]])



In [76]:
m10 = np.random.randint(1, 11, size=(3, 2))
m11 = np.random.randint(1, 11, size=(3, 2))
print(m10 * m11)
print(np.multiply(m10, m11))

print(m10.sum())
print(np.sum(m10))

[[50 10]
 [90 18]
 [90 54]]
[[50 10]
 [90 18]
 [90 54]]
42
42


In [77]:
print(np.array([[el.sum()] for el in m10[:]]))
print(np.array([[m10[el][:].sum()] for el in range(m10.shape[0])]))
print(np.sum(m10, axis=1).reshape((m10.shape[0], 1)))

[[15]
 [12]
 [15]]
[[15]
 [12]
 [15]]
[[15]
 [12]
 [15]]


In [78]:
print(m10 * m10)
print(m10 ** 2)
print(np.square(m10))

[[ 25 100]
 [ 81   9]
 [ 81  36]]
[[ 25 100]
 [ 81   9]
 [ 81  36]]
[[ 25 100]
 [ 81   9]
 [ 81  36]]


In [79]:
print(m10 ** 0.5)
print(np.sqrt(m10))

[[2.23606798 3.16227766]
 [3.         1.73205081]
 [3.         2.44948974]]
[[2.23606798 3.16227766]
 [3.         1.73205081]
 [3.         2.44948974]]


In [80]:
a = np.array([0, 2])
positive = a <= 1
print(positive)  # [ True False]

print(a.shape[0])  # 2

[ True False]
2


### pandas - DataFrame

In [81]:
import pandas as pd

In [88]:
df = pd.read_csv('bikes_rent.csv')
df.head(3)

season  yr  mnth  holiday  weekday  workingday  weathersit       temp  \
0       1   0     1        0        6           0           2  14.110847   
1       1   0     1        0        0           0           2  14.902598   
2       1   0     1        0        1           1           1   8.050924   

      atemp      hum  windspeed(mph)  windspeed(ms)   cnt  
0  18.18125  80.5833       10.749882       4.805490   985  
1  17.68695  69.6087       16.652113       7.443949   801  
2   9.47025  43.7273       16.636703       7.437060  1349

In [89]:
df.tail(3)

season  yr  mnth  holiday  weekday  workingday  weathersit       temp  \
728       1   1    12        0        6           0           2  10.386653   
729       1   1    12        0        0           0           1  10.489153   
730       1   1    12        0        1           1           2   8.849153   

        atemp      hum  windspeed(mph)  windspeed(ms)   cnt  
728  12.12000  75.2917        8.333661       3.725374  1341  
729  11.58500  48.3333       23.500518      10.505372  1796  
730  11.17435  57.7500       10.374682       4.637766  2729

In [92]:
# Видаліть з таблиці останній рядок таблиці
ndf = df.drop(df.shape[0]-1)
ndf.tail(3)

season  yr  mnth  holiday  weekday  workingday  weathersit       temp  \
727       1   1    12        0        5           1           2  10.386653   
728       1   1    12        0        6           0           2  10.386653   
729       1   1    12        0        0           0           1  10.489153   

       atemp      hum  windspeed(mph)  windspeed(ms)   cnt  
727  12.7523  59.0000       10.416557       4.656485  3095  
728  12.1200  75.2917        8.333661       3.725374  1341  
729  11.5850  48.3333       23.500518      10.505372  1796

In [ ]:
# Замініть відсутні дані в стовпцях середніми значеннями цих стовпців (метод fillna)
ndf2 = ndf.fillna({key: ndf[key].mean() for key in ndf.columns[1:]})

In [83]:
df['yr']  # Series - column from DataFrame
df[['yr']]  # DataFrame - consist column from DataFrame
df.loc[0]  # Series - line with index-name 0 from DataFrame
df.iloc[1]  # Series - line with number index 1 from DataFrame
df.iloc[:, 1:4]  # DataFrame with all lines and columns with indices 1-3
df.iloc[0:5, 5:8]  # DataFrame
df.iloc[0:5]['yr']  # Series
df.iloc[:, [0, 1, 3]]  # DataFrame
df[0:3]  # DataFrame - lines 0-2
df[df.index % 2 == 0]  # DataFrame
df[df['yr'] == 1]  # DataFrame
df[['yr', 'temp']]  # DataFrame
df[df.columns[:-1]]  # DataFrame
df.iloc[:, 1]  # Series

0      0
1      0
2      0
3      0
4      0
      ..
726    1
727    1
728    1
729    1
730    1
Name: yr, Length: 731, dtype: int64

In [84]:
df.describe()

season          yr        mnth     holiday     weekday  workingday  \
count  731.000000  731.000000  731.000000  731.000000  731.000000  731.000000   
mean     2.496580    0.500684    6.519836    0.028728    2.997264    0.683995   
std      1.110807    0.500342    3.451913    0.167155    2.004787    0.465233   
min      1.000000    0.000000    1.000000    0.000000    0.000000    0.000000   
25%      2.000000    0.000000    4.000000    0.000000    1.000000    0.000000   
50%      3.000000    1.000000    7.000000    0.000000    3.000000    1.000000   
75%      3.000000    1.000000   10.000000    0.000000    5.000000    1.000000   
max      4.000000    1.000000   12.000000    1.000000    6.000000    1.000000   

       weathersit        temp       atemp         hum  windspeed(mph)  \
count  731.000000  731.000000  731.000000  731.000000      731.000000   
mean     1.395349   20.310776   23.717699   62.789406       12.762576   
std      0.544894    7.505091    8.148059   14.242910        5.192357   
min      1.000000    2.424346    3.953480    0.000000        1.500244   
25%      1.000000   13.820424   16.892125   52.000000        9.041650   
50%      1.000000   20.431653   24.336650   62.666700       12.125325   
75%      2.000000   26.872076   30.430100   73.020850       15.625371   
max      3.000000   35.328347   42.044800   97.250000       34.000021   

       windspeed(ms)          cnt  
count     731.000000   731.000000  
mean        5.705220  4504.348837  
std         2.321125  1937.211452  
min         0.670650    22.000000  
25%         4.041864  3152.000000  
50%         5.420351  4548.000000  
75%         6.984967  5956.000000  
max        15.198937  8714.000000

In [85]:
df.filter(items=[col for col in ('yr', 'season', 'temp')])

yr  season       temp
0     0       1  14.110847
1     0       1  14.902598
2     0       1   8.050924
3     0       1   8.200000
4     0       1   9.305237
..   ..     ...        ...
726   1       1  10.420847
727   1       1  10.386653
728   1       1  10.386653
729   1       1  10.489153
730   1       1   8.849153

[731 rows x 3 columns]

In [86]:
df = pd.DataFrame({})
df[df.columns[:-1]]

Empty DataFrame
Columns: []
Index: []

#### corrwith

- https://www.statology.org/pandas-corrwith/

In [93]:
# Data for matrix
data = {'A': [45,37,42,35,39],
        'B': [38,31,26,28,33],
        'C': [10,15,17,21,12]
        }

df = pd.DataFrame(data,columns=['A','B','C'])
print("Original dataframe")
print(df) # original df
print("\n")

corrMatrix = df.corrwith(df["B"]) # finding correlations
print("Between column B and the rest of the dataframe")
print("Correlation Coefficients Matrix")
print(corrMatrix) # printing correlations
print('\n')

corrMatrix = df.corrwith(df["C"]) # finding correlations
print("Between column C and the rest of the dataframe")
print("Correlation Coefficients Matrix")
print(corrMatrix) # printing correlations
print('\n')

corrMatrix = df.corrwith(df["C"]) # finding correlations
print("Between column C and the rest of the dataframe")
print("Correlation Coefficients Matrix")
print(corrMatrix) # printing correlations

Original dataframe
    A   B   C
0  45  38  10
1  37  31  15
2  42  26  17
3  35  28  21
4  39  33  12


Between column B and the rest of the dataframe
Correlation Coefficients Matrix
A    0.518457
B    1.000000
C   -0.860941
dtype: float64


Between column C and the rest of the dataframe
Correlation Coefficients Matrix
A   -0.701886
B   -0.860941
C    1.000000
dtype: float64


Between column C and the rest of the dataframe
Correlation Coefficients Matrix
A   -0.701886
B   -0.860941
C    1.000000
dtype: float64
